checklist/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("details/<int:checklist_id>", views.checklist_detail, name = "checklist_detail"),
    path("update/<int:checklist_id>", views.checklist_update, name="checklist_update"),
    path("create", views.create, name ="checklist_create"),
    path("books",views.book, name="book"),
    path("updatev2/<int:checklist_id>",views.checklist_updatev2, name="checklist_updatev2"),
    path("editpump/<int:pump_id>", views.edit_pump, name="editpump"),
    path("delete/<int:pump_id>", views.delete_pump, name="deletepump"),
    path("allpumpsview", views.allpumpsview, name="allpumpsview"),
    path("editpumpinline/<int:pump_id>", views.editpumpinline, name="editpumpinline"),
    path("payment-method-ajax/<slug:method>", views.payment_method_ajax, name="payment-method-ajax"),
    path("main", views.main_ajax, name="main_ajax"),
    path("updatev3/<int:checklist_id>", views.checklist_updatev3, name = "checklist_updatev3"),
    path("addpumpajax/<int:checklist_id>", views.add_pump_ajax, name="add_pump_ajax"),
    path("editpumpajax/<int:pump_id>", views.edit_pump_ajax, name ="edit_pump_ajax"),
    path("deletepumpajax/<int:pump_id>", views.delete_pump_ajax, name = "delete_pump_ajax"),
]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("checklist.urls")),
]

checklist/models.py
from django.db import models

# Create your models here.
class Motor(models.Model):
    rating = models.CharField(max_length = 10)
    pole = models.CharField(max_length = 10)
    voltage = models.CharField(max_length = 10)

    def __str__(self):
        return f"{self.rating} kW - {self.pole}P"
    

class Checklist(models.Model):
    dateCreated = models.DateTimeField(auto_now_add = True)
    dateEdited = models.DateTimeField(auto_now = True)
    customer = models.CharField(max_length = 20)
    salesOrder = models.CharField(max_length = 20)
    deliveryOrder = models.CharField(max_length = 20)
    customerPO = models.CharField(max_length = 20)
    remarks = models.TextField(max_length = 300, blank = True)

    def __str__(self):
        return f"{self.salesOrder}"
    


class Pump(models.Model):
    serialnumber = models.CharField(max_length = 20, null=True, blank = True)
    model = models.CharField(max_length = 20)
    has_motor = models.BooleanField(default = False)
    motor = models.ForeignKey(Motor, on_delete = models.SET_NULL, blank = True, null = True)
    shipmentBatch = models.CharField(max_length = 20, null=True, blank = True)
    checklist = models.ForeignKey(Checklist, on_delete = models.CASCADE, null = True, blank = True, related_name = "pumps")

class QualityCheck(models.Model):
    canShaftBeTurnedByHand = models.BooleanField()
    isTheYellowShaftCoverInstalled = models.BooleanField()
    isTheWireMeshProvided = models.BooleanField()
    inletCover = models.BooleanField()
    catalogProvided = models.BooleanField()
    pump = models.OneToOneField(Pump, on_delete = models.CASCADE, null = True, blank = True, related_name = "qualitycheck")

    def __str__(self):

        return f"{self.canShaftBeTurnedByHand} - {self.isTheYellowShaftCoverInstalled} - {self. isTheWireMeshProvided}"

class Impeller(models.Model):
    size =  models.CharField(max_length = 10, blank = True, null = True)
    quantity = models.PositiveIntegerField(blank = True, null = True)
    pump = models.ForeignKey(Pump, on_delete = models.CASCADE)
    

    def __str__(self):
        return f"{self.size} x {self.quantity}"
    
class Baseplate(models.Model):
    dimension_A = models.DecimalField(max_digits = 10, decimal_places = 2)
    dimension_B = models.DecimalField(max_digits = 10, decimal_places = 2)
    dimension_C = models.DecimalField(max_digits = 10, decimal_places = 2)
    pump = models.OneToOneField(Pump, on_delete = models.CASCADE, blank = True, null = True, related_name = "baseplate")
    
    UNITS = {
        "mm":"millimeters",
        "cm":"centimeters",
        "in": "inches",
    }

    unit = models.CharField(max_length = 10, blank = True, null = True, choices = UNITS)

    def __str__(self):
        return f"{self.dimension_A}{self.unit} x {self.dimension_B}{self.unit} x {self.dimension_C}{self.unit}"
    
    
class Book(models.Model):

    name = models.CharField(max_length=255)
    isbn_number = models.CharField(max_length=13)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.name

checklist/forms.py
from django import forms
from .models import Checklist, Pump, Book, Baseplate, QualityCheck
from django.forms import ModelForm, inlineformset_factory, BaseFormSet


class ChecklistForm(ModelForm):
    class Meta:
        model = Checklist
        fields = ['customer','salesOrder','deliveryOrder','customerPO', 'remarks']

        widgets = {
            "customer": forms.TextInput(attrs={"class":"form-control"}),
            "salesOrder": forms.TextInput(attrs={"class":"form-control"}),
            "deliveryOrder": forms.TextInput(attrs={"class":"form-control"}),
            "customerPO": forms.TextInput(attrs={"class":"form-control"}),
            "remarks" : forms.Textarea(attrs={"rows": 3, "class":"form-control"}),
        }
        
        labels = {
            "customer": "Customer",
            "salesOrder": "Sales Order",
            "deliveryOrder": "Delivery Order",
            "customerPO": "Customer Purchase Order"
        }


class PumpForm(ModelForm):
    class Meta:
        model = Pump
        fields = ['model','serialnumber','has_motor','shipmentBatch']

        # widgets = {
        #     "serialnumber": forms.TextInput(attrs={"required":True}),
        #     "model": forms.TextInput(attrs={"required":True}),
        #     "shipmentBatch": forms.TextInput(attrs={"required":True}),
        # }

class PumpFormComplete(ModelForm):
    class Meta:
        model = Pump
        fields = ['model','serialnumber','has_motor','shipmentBatch', 'motor']

        # widgets = {
        #     "serialnumber": forms.TextInput(attrs={"required":True}),
        #     "model": forms.TextInput(attrs={"required":True}),
        #     "shipmentBatch": forms.TextInput(attrs={"required":True}),
        # }

        widgets = {
            "serialnumber" : forms.TextInput(attrs = {"class": "form-control"}),
            "model": forms.TextInput(attrs={"class":"form-control"}),
            "shipmentBatch": forms.TextInput(attrs={"class":"form-control"}),
            "motor": forms.Select(attrs={"class":"form-control"}),
        }


class BookForm(ModelForm):
    class Meta:
        model = Book

        fields = ["name"]

        widgets = {
            "name" : forms.TextInput(attrs={"class":"form-control", "placeholder": "Enter Book Name Here"},)
        }


class BaseplateForm(ModelForm):
    class Meta:
        model = Baseplate

        fields = ["dimension_A", "dimension_B", "dimension_C", "unit"]

        
        widgets = {
            "dimension_A" : forms.TextInput(attrs = {"class": "form-control"}),
            "dimension_B" : forms.TextInput(attrs = {"class": "form-control"}),
            "dimension_C": forms.TextInput(attrs = {"class": "form-control"}),
            "unit": forms.Select(attrs = {"class": "form-control"}),
        }

class QualityCheckForm(ModelForm):
    class Meta:
        model = QualityCheck

        exclude = ["pump"]

        widgets = {
            "canShaftBeTurnedByHand" : forms.CheckboxInput(attrs={"class" : "form-check-input"}),
            "isTheYellowShaftCoverInstalled": forms.CheckboxInput(attrs={"class" : "form-check-input"}),
            "inletCover": forms.CheckboxInput(attrs={"class" : "form-check-input"}),
            "catalogProvided": forms.CheckboxInput(attrs={"class" : "form-check-input"}),

        }

checklist/views.py
from django.shortcuts import render, reverse
from .models import Checklist, Pump, Book, Baseplate, QualityCheck
from .forms import ChecklistForm, PumpForm, BookForm, PumpFormComplete, BaseplateForm, QualityCheckForm
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect, JsonResponse

# Create your views here.

def index(request):
    
    checklists = Checklist.objects.all().order_by("-dateCreated")

    return render(request, "checklist/index.html",{
        "checklists": checklists
    })

def checklist_detail(request, checklist_id):

    try: 
        checklist = Checklist.objects.get(id = checklist_id)

    except Checklist.DoesNotExist:
        checklist= None
    
    return render(request, "checklist/detail.html",{
        "checklist": checklist,
    })

            
def checklist_update(request, checklist_id):
    
    try: 
        checklist = Checklist.objects.get(id = checklist_id)
    except Checklist.DoesNotExist:
        checklist= None
    pumps = checklist.pumps.all()

    PumpFormSet = modelformset_factory(Pump, form = PumpForm, extra = 0)

    #Instantiate the form
    formset = PumpFormSet(queryset = pumps )
    form = ChecklistForm(instance = checklist) 
    
    #if form submitted
    if request.method == "POST":
        message = None
        try: 
            c = Checklist.objects.get(id = checklist_id)

        except Checklist.DoesNotExist:
            c= None
        else:
            pumps = c.pumps.all()
        
        form = ChecklistForm(request.POST, instance = c)
        sub_formset = PumpFormSet(request.POST, queryset = pumps)

        # if form.is_valid():
        #     form.save()
        #     message = "Data saved."
        if all([form.is_valid(), sub_formset.is_valid()]):
            checklist = form.save(commit = False)
            checklist.save()

            for pump in sub_formset:
                if pump.is_valid():
                    if pump.cleaned_data != {}:
                        print(pump.cleaned_data)
                        pump = pump.save(commit = False)
                        if pump.checklist is None:
                            pump.checklist = checklist 
                        pump.save()
                        message = "Data saved."
                 
        else:
            # If the form is invalid, re-render the page with existing information.
            print("form invalid")
            return render(request, "checklist/update.html", {
                "form": form,
                "formset": sub_formset,
                "checklist": checklist,
            })
        
        # if request.htmx:
        #     return render(request, "checklist/partials/forms.html",{
        #         "form": form,
        #         "formset":formset,
        #         "checklist": checklist,
        #         "message": message,
        #     })
        
    
    return render(request, "checklist/update.html",{
        "form": form,
        "formset":formset,
        "checklist": checklist,
    })


def checklist_updatev2(request, checklist_id):

    try:
        checklist = Checklist.objects.get(id = checklist_id)

    except Checklist.DoesNotExist:
        checklist = None
    else:
        pumps = checklist.pumps.all()


    form = ChecklistForm(instance = checklist) 
    PumpFormSet = modelformset_factory(Pump, form = PumpForm, extra = 0)
 
    formset = PumpFormSet(queryset = Pump.objects.none())

    if request.method == "POST":
        print(request.POST)
        try: 
            c = Checklist.objects.get(id = checklist_id)

        except Checklist.DoesNotExist:
            c= None

        else:
            pumps = c.pumps.all()
            
        form = ChecklistForm(request.POST, instance = c)
        formset = PumpFormSet(request.POST, queryset = pumps)

        if all([form.is_valid(), formset.is_valid()]):
            checklist = form.save(commit = False)
            checklist.save()

            for pump in formset:
                if pump.is_valid():
                    if pump.cleaned_data !={}:
                        print(pump.cleaned_data)
                        pump = pump.save(commit = False)
                        if pump.checklist is None:
                            pump.checklist = checklist 
                        pump.save()
            
            return HttpResponseRedirect(reverse('checklist_updatev2', args=[checklist.id,]))

        else:
            return render(request, "checklist/updatev2.html",{
                "form": form,
                "formset": formset,
                "checklist": checklist,
                "pumps":pumps,
            })

    return render(request, "checklist/updatev2.html",{
        "form": form,
        "checklist": checklist,
        "pumps":pumps,
        "formset": formset,
    })




def create(request):
    PumpFormSet = modelformset_factory(Pump, form = PumpForm, extra = 1)
    
    formset = PumpFormSet(queryset= Pump.objects.none())
    #instantiate empty form
    form = ChecklistForm()

    if request.method == "POST":
        form = ChecklistForm(request.POST)
        sub_formset = PumpFormSet(request.POST)
        print(sub_formset)
        if all([form.is_valid(), sub_formset.is_valid()]):
            #Saves the form data into a new 'Checklist' object without committing it to database yet, allowing for further modifications
            checklist = form.save(commit = False)
            checklist.save()
            print(checklist)

            for pump in sub_formset:
                if pump.is_valid():
                    print("Pump is valid")
                    if pump.cleaned_data !={}:
                        pump = pump.save(commit=False)
                        pump.checklist = checklist
                        pump.save()
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "checklist/create.html",{
                "form": form,
                "formset": sub_formset,
            })
        
    return render(request, "checklist/create.html",{
        "form": form,
        "formset": formset,
    })


def book(request):

    BookFormSet = modelformset_factory(Book,form = BookForm, extra = 1)
    formset = BookFormSet()
    return render(request, "checklist/books.html", {
        "formset": formset,
    })

def edit_pump(request, pump_id):

    pump = Pump.objects.get(id = pump_id)

    pumpform = PumpFormComplete(instance = pump)
    
    #BaseplateFormSet = modelformset_factory(Baseplate , form = BaseplateForm, extra=0)
    #formset = BaseplateFormSet()

    baseplateform = BaseplateForm()
    qualitycheckform = QualityCheckForm()
    try:
        baseplate = pump.baseplate
    except Baseplate.DoesNotExist:
        print("Pump has no baseplate")
    else:
        baseplateform = BaseplateForm(instance = baseplate)
        #formset = BaseplateFormSet(queryset=baseplate)

    try:
        qualitycheck = pump.qualitycheck
    except QualityCheck.DoesNotExist:
        print("Pump has not passed quality check.")
    else:
        qualitycheckform = QualityCheckForm(instance = qualitycheck)

    #if form is submitted
    if request.method == "POST":

        p = Pump.objects.get(id = pump_id)

        pumpform = PumpFormComplete(request.POST, instance = p)
        
        try: 
            b = p.baseplate
        except Baseplate.DoesNotExist:
            baseplateform = BaseplateForm(request.POST)
        else:
            baseplateform = BaseplateForm(request.POST, instance = b)

        try: 
            q = p.qualitycheck
        
        except QualityCheck.DoesNotExist:
            qualitycheckform = QualityCheckForm(request.POST)
        else:
            qualitycheckform = QualityCheckForm(request.POST, instance = q)

        if all([pumpform.is_valid(),baseplateform.is_valid(), qualitycheckform.is_valid()]):
            print("All forms are valid")
            pump = pumpform.save(commit = False)
            pump.save()
            print("successfully saved pump")

            baseplate = baseplateform.save(commit = False)
            baseplate.pump = pump
            baseplate.save()
            print("successfully saved baseplate")
            qc = qualitycheckform.save(commit = False)
            qc.pump = pump
            qc.save()
            print("successfully saved qcform")

            return HttpResponseRedirect(reverse('editpump', args=[pump.id,]))
        else:

            return render(request,"checklist/pump.html",{
                "pump": pump,
                "pumpform": pumpform,
                "baseplateform": baseplateform,
                "qualitycheckform": qualitycheckform,
            })
    return render(request, "checklist/pump.html",{
        "pump": pump,
        "pumpform": pumpform,
        "baseplateform": baseplateform,
        "qualitycheckform": qualitycheckform,
    })


def delete_pump(request, pump_id):

    try:
        pump = Pump.objects.get(id = pump_id)
    
    except Pump.DoesNotExist:
        pump = None

        return render(request, "checklist/error.html")


    if request.method == "POST":
        pump = Pump.objects.get(id = pump_id)
        checklist_id = pump.checklist.id
        pump.delete()

        return HttpResponseRedirect(reverse('checklist_updatev2', args=[checklist_id,]))


    return render(request, "checklist/delete.html",{
        "pump":pump,
    })


def allpumpsview(request):

    pumps = Pump.objects.all()

    return render(request, "checklist/allpump.html",{
        "pumps": pumps
    })


def delete_pump(request, pump_id):
    try:
        pump = Pump.objects.get(id = pump_id)
    
    except Pump.DoesNotExist:
        pump = None

        return render(request, "checklist/error.html")
    if request.method == "POST":
        pump = Pump.objects.get(id = pump_id)
        checklist_id = pump.checklist.id
        pump.delete()

checklist/templates/checklist/ajax_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        var ach = 'ACH';
        var creditCard = 'Credit Card';
    
        var formUrls = {
            ach: '{% url "payment-method-ajax" slugs.0 %}',
            creditCard: '{% url "payment-method-ajax" slugs.1 %}',
        };
    
        function load_payment_form(btn) {
            var get_url, type;
    
            if (btn.innerText === ach) {
                get_url = formUrls.ach;
                type = ach;
            } else if (btn.innerText === creditCard) {
                console.log('Load credit card form');
                get_url = formUrls.creditCard;
                type = creditCard;
            }
            fetch(get_url)
            .then(response => response.text()) 
            .then(function(data) {
                //console.log(data)
                document.getElementById('form-fields').innerHTML = data;
                document.getElementById("id-form").style.display = "block";


                document.getElementById("cancel-button").addEventListener("click", function() {
                    document.getElementById("id-form").style.display = "none";
                });
            })
            .catch(function(error) {
                console.log('Error fetching form:', error);
            });
        }
    </script>
    

    
</head>
<body>

    <button id="btn_ach" onclick="load_payment_form(this)">ACH</button>
    <button id="btn_credit_card" onclick="load_payment_form(this)">Credit Card</button>

    <form id="id-form" style="display: none;">
        {% csrf_token %}
    
        <div id="form-fields"></div>
        <input type="submit" value="Save Payment Details"/>
    </form>

    <div>
        <button id="cancel-button">Cancel</button>
    </div>
    
</body>
</html>

checklist/templates/checklist/allpump.html
{% extends 'checklist/layout.html' %}

{% load static %}

{% block body %}

    <div class=container>
        <div class="row">
            {% for pump in pumps %}
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <h5 class="card-header">{{ pump.model }} - {{ pump.serialnumber }}</h5>
                            <div class="card-body">
                            <p class="card-text">
                                {% if pump.had_motor %}
                                    {{ pump.motor }}
                                {% else %}
                                    Bare pump
                                {% endif %}
                            </p>
                            <p class="card-text"> Shipment Batch: {{ shipmentNumber }}</p>
                            <h5 class="card-title">Baseplate</h5>
                            <p class="card-text"> {{ pump.baseplate }}</p>
                            <h5 class="card-title">Quality Check </h5>
                            <p class="card-text">
                                <ul>
                                    <li> Can Shaft be turned by hand? - {{ pump.qualitycheck.canShaftBeTurnedByHand }}</li>
                                    <li> Is the yellow cover installed? - {{ pump.qualitycheck.isTheYellowShaftCoverInstalle }}</li>
                                    <li> Is the wire mesh provided? - {{ pump.qualitycheck.isTheWireMeshProvided }}</li>
                                    <li> Is the inlet & outlet cover installed?  - {{ pump.qualitycheck.inletCover }}</li>
                                    <li> Is the catalog attached to the pump? - {{ pump.qualitycheck.catalogProvided }}</li>
                                </ul>
                            </p>
                            <a href="{% url 'editpump' pump.id %}" class="btn btn-primary">Edit</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    


    </div>




{% endblock %}

{% block script %}

{% endblock %}

checklist/templates/checklist/books.html
{% extends 'checklist/layout.html' %}
{% load static %}

{% block body %}
    <div class="container">
        <form class="form-horizontal" method="POST" action="">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for form in formset %}
            <div class="row form-row spacer">
                <div class="col-2">
                    <label>{{form.name.label}}</label>
                </div>
                <div class="col-4">
                    <div class="input-group">
                        {{form.name}}
                        <div class="input-group-append">
                            <button class="btn btn-success add-form-row">+</button>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row spacer">
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-block btn-primary">Create</button>
                </div>
            </div>
            </form>
    </div>

{% endblock %}

{% block script %}
    <script src="{% static 'checklist/books.js' %}"></script>
{% endblock %}

checklist/templates/checklist/create.html
{% extends 'checklist/layout.html' %}
{% load static %}

{% block body %}
    <div class="container">
        <h1>Create Checklist</h1>
        <form method = "POST" action ="{% url 'checklist_create' %}">
            {% csrf_token %}
            {{ form.as_p }}
        
            {{ formset.management_form }}
            <div class="pump-form-list">
                {% for form in formset %}
                    <div class="pump-form">
                        {{ form.as_p }}
                    </div>
                    <hr>
                {% endfor %}
            </div>
        
            <div id="empty-form" class="hidden"> 
                {{ formset.empty_form }}
                <button type="button" id="remove-button">Remove</button>
            </div>
            <button id="add-more" type="button">Add Pump</button>
            <!-- <div class="htmx-indicator">Loading...</div> -->
            <button class="" type="submit">Save</button>
            {% if message %}
                {{ message }}
            {% endif %}
        </form>

  
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'checklist/pump.js' %}"></script>
{% endblock %}

checklist/templates/checklist/delete.html
{% extends 'checklist/layout.html' %}


{% block body %}

<div class="container">

    <form method="POST" action="{% url 'deletepump' pump.id %}">
        {% csrf_token %}
        
        <h3>Are you sure you want to delete {{ pump.model }} - {{ pump.serialnumber }}?</h3>

        <button type="submit">Delete</button>
    </form>

    <button class="my-5" type="button">Cancel</button>
</div>

{% endblock %}

checklist/templates/checklist/detail.html
{% extends 'checklist/layout.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Checklist : {{ checklist.salesOrder }}</h1>
            <ul>
                <li>Customer: {{ checklist.customer }}</li>
                <li>Date Created: {{ checklist.dateCreated }}</li>
                <li>Last Updated: {{ checklist.dateEdited }}</li>
                <li>Customer Purchase Order: {{ checklist.customerPO }}</li>
                <li>Delivery Order: {{ checklist.deliveryOrder }}</li>
            </ul>
            <div><strong>Remarks:</strong></div>
            <div><p>{{ checklist.remarks }}</p></div>
            <a href="{% url 'checklist_updatev2' checklist.id %}" class="btn btn-primary">Edit Checklist</a>
        </div>
    </div>



    <div class="row">
        {% for pump in checklist.pumps.all %}
            <div class="row">
                <div class="col">
                    <div class="card">
                        <h5 class="card-header">{{ pump.model }} - {{ pump.serialnumber }}</h5>
                        <div class="card-body">
                        <p class="card-text">
                            {% if pump.had_motor %}
                                {{ pump.motor }}
                            {% else %}
                                Bare pump
                            {% endif %}
                        </p>
                        <p class="card-text"> Shipment Batch: {{ shipmentNumber }}</p>
                        <h5 class="card-title">Baseplate</h5>
                        <p class="card-text"> {{ pump.baseplate }}</p>
                        <h5 class="card-title">Quality Check </h5>
                        <p class="card-text">
                            <ul>
                                <li> Can Shaft be turned by hand? - {{ pump.qualitycheck.canShaftBeTurnedByHand }}</li>
                                <li> Is the yellow cover installed? - {{ pump.qualitycheck.isTheYellowShaftCoverInstalle }}</li>
                                <li> Is the wire mesh provided? - {{ pump.qualitycheck.isTheWireMeshProvided }}</li>
                                <li> Is the inlet & outlet cover installed?  - {{ pump.qualitycheck.inletCover }}</li>
                                <li> Is the catalog attached to the pump? - {{ pump.qualitycheck.catalogProvided }}</li>
                            </ul>
                        </p>
                        <a href="{% url 'editpump' pump.id %}" class="btn btn-primary">Edit</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

checklist/templates/checklist/error.html
{% extends 'checklist/layout.html' %}


{% block body %}

<div class="container">
    <h2>Object does not exist!</h2>
</div>

{% endblock %}

checklist/templates/checklist/index.html
{% extends 'checklist/layout.html' %}

{% block body %}
    <div class="container my-5  ">
        <div class="row mb-5">
            <ul class="list-group">
                {% for checklist in checklists %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col">
                                {{ checklist.salesOrder }} - {{ checklist.customer }}
                            </div>
                            <div class="col">
                                <a href="{% url 'checklist_detail' checklist.id %}" >View</a>
                            </div>
                            <div class="col">
                                <a href="{% url 'checklist_update' checklist.id %}" >Edit</a>
                            </div>
                            <div class="col">
                                <a href="{% url 'checklist_updatev2' checklist.id %}" >Edit v2</a>
                            </div>
                            <div class="col">
                                <a href="{% url 'checklist_updatev3' checklist.id %}" >Edit v3</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>

        </div>

        <div class="row">
            <div class="col">
                <a href="{% url 'checklist_create' %}">
                    <button class="btn btn-primary">Create</button>
                </a>
            </div>
        </div>

    </div>

{% endblock %}

checklist/templates/checklist/pump.html
{% extends 'checklist/layout.html' %}

{% load static %}

{% block body %}
<div class="container">

    <h1> {{ pump.model }} - {{ pump.serialnumber }}</h1>

    <form action="{% url 'editpump' pump.id %}" method="POST">
        {% csrf_token %}
        {{ pumpform }}

        {{ baseplateform }}

        {{ qualitycheckform }}

        <button type="submit">Submit</button>
    </form>

</div>



{% endblock %}

{% block script %}

{% endblock %}

checklist/templates/checklist/trial.html
{% extends 'checklist/layout.html' %}

{% load static %}


{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ pump_form.as_p }}
        {{ pump_form.qualitycheck_set.management_form }}
        {% for qc_form in pump_form.qualitycheck_set.forms %}
            {{ qc_form.as_p }}
        {% endfor %}
        {{ pump_form.baseplate_set.management_form }}
        {% for bp_form in pump_form.baseplate_set.forms %}
            {{ bp_form.as_p }}
        {% endfor %}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

checklist/templates/checklist/update.html
{% extends 'checklist/layout.html' %}
{% load static %}

{% block body %}
<div class="container">
    <h1> {{ checklist.salesOrder }}</h1>
    <form method = "POST" action ="{% url 'checklist_update' checklist.id %}">
        <!-- hx-post="{% url 'checklist_update' checklist.id %}" hx-swap = "outerHTML" -->
        {% csrf_token %}
        {{ form.as_p }}
    
        {{ formset.management_form }}
        <div class="pump-form-list">
            {% for form in formset %}
                <div class="pump-form">
                    {{ form.as_p }}
                    <button type="button">Delete</button>
                </div>
                <hr>
            {% endfor %}
        </div>
    
        <div id="empty-form" class="hidden"> 
            {{ formset.empty_form }}
            <button type="button" id="remove-button">Remove</button>
        </div>
        <button id="add-more" type="button">Add Pump</button>
        <!-- <div class="htmx-indicator">Loading...</div> -->
        <button class="" type="submit">Save</button>
        {% if message %}
            {{ message }}
        {% endif %}
    </form>
    
</div>

{% endblock %}

{% block script %}
    <script src="{% static 'checklist/pump.js' %}"></script>
{% endblock %}